import Link from "next/link";
import Image from "next/image";

import "./globals.css";
import Header from "./blog/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Image src={"/image3.png"} alt={"image"} width={100} height={100} />
        {children}
      </body>
    </html>
  );
}
